import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import LayoutShell from "./LayoutShell";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.variable}>
        <LayoutShell>{children}</LayoutShell>
      </body>
    </html>
  );
}