import type { CategoryItem, Product } from "./types";

export const categories: CategoryItem[] = [
  { label: "All", href: "/products?cat=all&page=1" },
  { label: "Facial Cleanser", href: "/products?cat=facial-cleanser&page=1" },
  { label: "Pomade", href: "/products?cat=pomade&page=1" },
  { label: "Perfume", href: "/products?cat=perfume&page=1" },
  { label: "Baby Powder", href: "/products?cat=baby-powder&page=1" },
  { label: "Eye Liner", href: "/products?cat=eye-liner&page=1" },
  { label: "Lip Clippers", href: "/products?cat=lip-clippers&page=1" },
];

export const products: Product[] = [
  {
    id: "p1",
    title: "Deep Cleansing Facial Wash with Aloe Vera Extract",
    image: "/assets/products/p1.png",
    rating: 4.5,
    reviews: 11,
    priceFrom: 39.99,
    priceTo: 30.65,
    category: "facial-cleanser",
    href: "/products/p1",
    description:
      "A gentle deep cleansing facial wash infused with Aloe Vera. Removes dirt, oil, and impurities while keeping your skin hydrated and fresh.",
  },
  {
    id: "p2",
    title: "Oil Control Foam Facial Cleanser – Daily Use",
    image: "/assets/products/p2.png",
    rating: 4.0,
    reviews: 8,
    priceFrom: 29.99,
    priceTo: 22.50,
    category: "facial-cleanser",
    href: "/products/p2",
    description:
      "Foam-based cleanser that controls excess oil and gives a matte finish. Perfect for daily use on oily and combination skin types.",
  },
  {
    id: "p3",
    title: "Classic Hold Pomade for Men – Strong & Shiny Finish",
    image: "/assets/products/p3.png",
    rating: 4.5,
    reviews: 20,
    priceFrom: 19.99,
    priceTo: 14.99,
    category: "pomade",
    href: "/products/p3",
    description:
      "A classic water-based pomade that gives a strong hold and high-shine finish. Easy to wash out and perfect for all hair types.",
  },
  {
    id: "p4",
    title: "Matte Finish Hair Pomade – Medium Hold for Natural Look",
    image: "/assets/products/p4.png",
    rating: 3.5,
    reviews: 5,
    priceFrom: 15.00,
    priceTo: 11.00,
    category: "pomade",
    href: "/products/p4",
    description:
      "Achieve a natural, matte look with medium hold. This pomade keeps your hair styled all day without the greasiness.",
  },
  {
    id: "p5",
    title: "Floral Bliss Eau de Parfum – Long Lasting Women Perfume",
    image: "/assets/products/p1.png",
    rating: 5.0,
    reviews: 34,
    priceFrom: 59.99,
    priceTo: 49.99,
    category: "perfume",
    href: "/products/p5",
    description:
      "A luxurious floral fragrance with notes of rose, jasmine, and vanilla. Long-lasting scent that keeps you fresh all day.",
  },
  {
    id: "p6",
    title: "Oud & Amber Men's Perfume – Rich Oriental Fragrance",
    image: "/assets/products/p2.png",
    rating: 4.5,
    reviews: 18,
    priceFrom: 69.99,
    priceTo: 55.00,
    category: "perfume",
    href: "/products/p6",
    description:
      "A bold and masculine fragrance with deep oud and warm amber notes. Ideal for evenings and special occasions.",
  },
  {
    id: "p7",
    title: "Johnson's Soft & Gentle Baby Powder – Talc Free Formula",
    image: "/assets/products/p3.png",
    rating: 4.0,
    reviews: 42,
    priceFrom: 9.99,
    priceTo: 7.50,
    category: "baby-powder",
    href: "/products/p7",
    description:
      "A soft, talc-free baby powder that keeps your baby's skin dry, smooth, and comfortable. Dermatologist tested and hypoallergenic.",
  },
  {
    id: "p8",
    title: "Lavender Soothing Baby Powder – Calming Night Formula",
    image: "/assets/products/p4.png",
    rating: 4.5,
    reviews: 27,
    priceFrom: 12.99,
    priceTo: 10.00,
    category: "baby-powder",
    href: "/products/p8",
    description:
      "Infused with calming lavender, this baby powder soothes sensitive skin and helps baby sleep peacefully through the night.",
  },
  {
    id: "p9",
    title: "Precision Liquid Eye Liner – Waterproof Black",
    image: "/assets/products/p1.png",
    rating: 4.5,
    reviews: 15,
    priceFrom: 14.99,
    priceTo: 10.99,
    category: "eye-liner",
    href: "/products/p9",
    description:
      "A precision tip liquid eyeliner that delivers sharp, defined lines. Waterproof formula that lasts all day without smudging.",
  },
  {
    id: "p10",
    title: "Kohl Eye Liner Pencil – Smudge Proof & Long Lasting",
    image: "/assets/products/p2.png",
    rating: 4.0,
    reviews: 9,
    priceFrom: 8.99,
    priceTo: 6.50,
    category: "eye-liner",
    href: "/products/p10",
    description:
      "A smooth kohl pencil that glides effortlessly for bold, dramatic eyes. Smudge-proof and buildable for any look.",
  },
  {
    id: "p11",
    title: "Matte Lip Liner Clipper – Nude & Bold Shades Pack",
    image: "/assets/products/p3.png",
    rating: 3.5,
    reviews: 6,
    priceFrom: 11.99,
    priceTo: 8.99,
    category: "lip-clippers",
    href: "/products/p11",
    description:
      "Define and shape your lips perfectly with this matte lip liner. Comes in 6 versatile shades from nude to bold.",
  },
  {
    id: "p12",
    title: "Precision Lip Definer – Anti-Feather Formula",
    image: "/assets/products/p4.png",
    rating: 4.0,
    reviews: 13,
    priceFrom: 13.99,
    priceTo: 10.50,
    category: "lip-clippers",
    href: "/products/p12",
    description:
      "An anti-feather lip definer that keeps your lipstick in place all day. Smooth application with a creamy, long-wearing formula.",
  },
];